# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI_2MEMS_SIM_python.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(947, 774)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sliderM1_phase = QtWidgets.QSlider(self.centralwidget)
        self.sliderM1_phase.setGeometry(QtCore.QRect(80, 190, 22, 160))
        self.sliderM1_phase.setMinimum(-10000)
        self.sliderM1_phase.setMaximum(10000)
        self.sliderM1_phase.setProperty("value", 0)
        self.sliderM1_phase.setOrientation(QtCore.Qt.Vertical)
        self.sliderM1_phase.setObjectName("sliderM1_phase")
        self.sliderM1_x = QtWidgets.QSlider(self.centralwidget)
        self.sliderM1_x.setGeometry(QtCore.QRect(150, 190, 22, 160))
        self.sliderM1_x.setMinimum(-25000)
        self.sliderM1_x.setMaximum(25000)
        self.sliderM1_x.setOrientation(QtCore.Qt.Vertical)
        self.sliderM1_x.setObjectName("sliderM1_x")
        self.sliderM1_y = QtWidgets.QSlider(self.centralwidget)
        self.sliderM1_y.setGeometry(QtCore.QRect(220, 190, 22, 160))
        self.sliderM1_y.setMinimum(-25000)
        self.sliderM1_y.setMaximum(25000)
        self.sliderM1_y.setOrientation(QtCore.Qt.Vertical)
        self.sliderM1_y.setObjectName("sliderM1_y")
        self.spinBox_M1_phase = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_M1_phase.setGeometry(QtCore.QRect(60, 360, 61, 22))
        self.spinBox_M1_phase.setMinimum(-10000)
        self.spinBox_M1_phase.setMaximum(10000)
        self.spinBox_M1_phase.setProperty("value", 0)
        self.spinBox_M1_phase.setObjectName("spinBox_M1_phase")
        self.spinBox_M1_x = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_M1_x.setGeometry(QtCore.QRect(130, 360, 61, 22))
        self.spinBox_M1_x.setMinimum(-25000)
        self.spinBox_M1_x.setMaximum(25000)
        self.spinBox_M1_x.setProperty("value", 0)
        self.spinBox_M1_x.setObjectName("spinBox_M1_x")
        self.spinBox_M1_y = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_M1_y.setGeometry(QtCore.QRect(200, 360, 61, 22))
        self.spinBox_M1_y.setMinimum(-25000)
        self.spinBox_M1_y.setMaximum(25000)
        self.spinBox_M1_y.setProperty("value", 0)
        self.spinBox_M1_y.setObjectName("spinBox_M1_y")
        self.spinBox_M1_1 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_M1_1.setGeometry(QtCore.QRect(60, 110, 41, 22))
        self.spinBox_M1_1.setReadOnly(True)
        self.spinBox_M1_1.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_M1_1.setMaximum(50000)
        self.spinBox_M1_1.setProperty("value", 25000)
        self.spinBox_M1_1.setObjectName("spinBox_M1_1")
        self.spinBox_M1_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_M1_2.setGeometry(QtCore.QRect(110, 110, 41, 22))
        self.spinBox_M1_2.setReadOnly(True)
        self.spinBox_M1_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_M1_2.setMaximum(50000)
        self.spinBox_M1_2.setProperty("value", 25000)
        self.spinBox_M1_2.setObjectName("spinBox_M1_2")
        self.spinBox_M1_3 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_M1_3.setGeometry(QtCore.QRect(160, 110, 41, 22))
        self.spinBox_M1_3.setReadOnly(True)
        self.spinBox_M1_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_M1_3.setMaximum(50000)
        self.spinBox_M1_3.setProperty("value", 25000)
        self.spinBox_M1_3.setObjectName("spinBox_M1_3")
        self.spinBox_M1_4 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_M1_4.setGeometry(QtCore.QRect(210, 110, 41, 22))
        self.spinBox_M1_4.setReadOnly(True)
        self.spinBox_M1_4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_M1_4.setMaximum(50000)
        self.spinBox_M1_4.setProperty("value", 25000)
        self.spinBox_M1_4.setObjectName("spinBox_M1_4")
        self.label_M1_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_M1_1.setGeometry(QtCore.QRect(60, 90, 31, 16))
        self.label_M1_1.setObjectName("label_M1_1")
        self.label_M1_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_M1_2.setGeometry(QtCore.QRect(110, 90, 31, 16))
        self.label_M1_2.setObjectName("label_M1_2")
        self.label_M1_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_M1_3.setGeometry(QtCore.QRect(160, 90, 31, 16))
        self.label_M1_3.setObjectName("label_M1_3")
        self.label_M1_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_M1_4.setGeometry(QtCore.QRect(210, 90, 31, 16))
        self.label_M1_4.setObjectName("label_M1_4")
        self.label_M1_phase = QtWidgets.QLabel(self.centralwidget)
        self.label_M1_phase.setGeometry(QtCore.QRect(70, 160, 61, 16))
        self.label_M1_phase.setObjectName("label_M1_phase")
        self.label_M1_x = QtWidgets.QLabel(self.centralwidget)
        self.label_M1_x.setGeometry(QtCore.QRect(150, 160, 31, 16))
        self.label_M1_x.setObjectName("label_M1_x")
        self.label_M1_y = QtWidgets.QLabel(self.centralwidget)
        self.label_M1_y.setGeometry(QtCore.QRect(210, 160, 31, 16))
        self.label_M1_y.setObjectName("label_M1_y")
        self.spinBox_M2_1 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_M2_1.setGeometry(QtCore.QRect(330, 110, 41, 22))
        self.spinBox_M2_1.setReadOnly(True)
        self.spinBox_M2_1.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_M2_1.setMaximum(50000)
        self.spinBox_M2_1.setProperty("value", 25000)
        self.spinBox_M2_1.setObjectName("spinBox_M2_1")
        self.label_M2_x = QtWidgets.QLabel(self.centralwidget)
        self.label_M2_x.setGeometry(QtCore.QRect(420, 160, 31, 16))
        self.label_M2_x.setObjectName("label_M2_x")
        self.sliderM2_x = QtWidgets.QSlider(self.centralwidget)
        self.sliderM2_x.setGeometry(QtCore.QRect(420, 190, 22, 160))
        self.sliderM2_x.setMinimum(-25000)
        self.sliderM2_x.setMaximum(25000)
        self.sliderM2_x.setOrientation(QtCore.Qt.Vertical)
        self.sliderM2_x.setObjectName("sliderM2_x")
        self.spinBox_M2_4 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_M2_4.setGeometry(QtCore.QRect(480, 110, 41, 22))
        self.spinBox_M2_4.setReadOnly(True)
        self.spinBox_M2_4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_M2_4.setMaximum(50000)
        self.spinBox_M2_4.setProperty("value", 25000)
        self.spinBox_M2_4.setObjectName("spinBox_M2_4")
        self.label_M2_phase = QtWidgets.QLabel(self.centralwidget)
        self.label_M2_phase.setGeometry(QtCore.QRect(340, 160, 61, 16))
        self.label_M2_phase.setObjectName("label_M2_phase")
        self.label_M2_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_M2_2.setGeometry(QtCore.QRect(380, 90, 31, 16))
        self.label_M2_2.setObjectName("label_M2_2")
        self.sliderM2_phase = QtWidgets.QSlider(self.centralwidget)
        self.sliderM2_phase.setGeometry(QtCore.QRect(350, 190, 22, 160))
        self.sliderM2_phase.setMinimum(-10000)
        self.sliderM2_phase.setMaximum(10000)
        self.sliderM2_phase.setProperty("value", 0)
        self.sliderM2_phase.setOrientation(QtCore.Qt.Vertical)
        self.sliderM2_phase.setObjectName("sliderM2_phase")
        self.spinBox_M2_3 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_M2_3.setGeometry(QtCore.QRect(430, 110, 41, 22))
        self.spinBox_M2_3.setReadOnly(True)
        self.spinBox_M2_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_M2_3.setMaximum(50000)
        self.spinBox_M2_3.setProperty("value", 25000)
        self.spinBox_M2_3.setObjectName("spinBox_M2_3")
        self.spinBox_M2_y = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_M2_y.setGeometry(QtCore.QRect(470, 360, 61, 22))
        self.spinBox_M2_y.setMinimum(-25000)
        self.spinBox_M2_y.setMaximum(25000)
        self.spinBox_M2_y.setProperty("value", 0)
        self.spinBox_M2_y.setObjectName("spinBox_M2_y")
        self.spinBox_M2_x = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_M2_x.setGeometry(QtCore.QRect(400, 360, 61, 22))
        self.spinBox_M2_x.setMinimum(-25000)
        self.spinBox_M2_x.setMaximum(25000)
        self.spinBox_M2_x.setProperty("value", 0)
        self.spinBox_M2_x.setObjectName("spinBox_M2_x")
        self.label_M2_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_M2_1.setGeometry(QtCore.QRect(330, 90, 31, 16))
        self.label_M2_1.setObjectName("label_M2_1")
        self.label_M2_y = QtWidgets.QLabel(self.centralwidget)
        self.label_M2_y.setGeometry(QtCore.QRect(480, 160, 31, 16))
        self.label_M2_y.setObjectName("label_M2_y")
        self.spinBox_M2_phase = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_M2_phase.setGeometry(QtCore.QRect(330, 360, 61, 22))
        self.spinBox_M2_phase.setMinimum(-10000)
        self.spinBox_M2_phase.setMaximum(10000)
        self.spinBox_M2_phase.setProperty("value", 0)
        self.spinBox_M2_phase.setObjectName("spinBox_M2_phase")
        self.spinBox_M2_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_M2_2.setGeometry(QtCore.QRect(380, 110, 41, 22))
        self.spinBox_M2_2.setReadOnly(True)
        self.spinBox_M2_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_M2_2.setMaximum(50000)
        self.spinBox_M2_2.setProperty("value", 25000)
        self.spinBox_M2_2.setObjectName("spinBox_M2_2")
        self.label_M2_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_M2_3.setGeometry(QtCore.QRect(430, 90, 31, 16))
        self.label_M2_3.setObjectName("label_M2_3")
        self.label_M2_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_M2_4.setGeometry(QtCore.QRect(480, 90, 31, 16))
        self.label_M2_4.setObjectName("label_M2_4")
        self.sliderM2_y = QtWidgets.QSlider(self.centralwidget)
        self.sliderM2_y.setGeometry(QtCore.QRect(490, 190, 22, 160))
        self.sliderM2_y.setMinimum(-25000)
        self.sliderM2_y.setMaximum(25000)
        self.sliderM2_y.setOrientation(QtCore.Qt.Vertical)
        self.sliderM2_y.setObjectName("sliderM2_y")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(570, 70, 361, 221))
        self.groupBox.setObjectName("groupBox")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 331, 191))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.checkBox_pos1 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_pos1.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.checkBox_pos1.setChecked(True)
        self.checkBox_pos1.setObjectName("checkBox_pos1")
        self.checkBox_pos2 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_pos2.setGeometry(QtCore.QRect(10, 40, 70, 17))
        self.checkBox_pos2.setObjectName("checkBox_pos2")
        self.checkBox_pos3 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_pos3.setGeometry(QtCore.QRect(10, 60, 70, 17))
        self.checkBox_pos3.setObjectName("checkBox_pos3")
        self.pushButton_Auto1Pos = QtWidgets.QPushButton(self.tab)
        self.pushButton_Auto1Pos.setGeometry(QtCore.QRect(140, 20, 171, 51))
        self.pushButton_Auto1Pos.setObjectName("pushButton_Auto1Pos")
        self.spinBox_frameNo1Pos = QtWidgets.QSpinBox(self.tab)
        self.spinBox_frameNo1Pos.setGeometry(QtCore.QRect(10, 130, 81, 22))
        self.spinBox_frameNo1Pos.setMaximum(999)
        self.spinBox_frameNo1Pos.setProperty("value", 3)
        self.spinBox_frameNo1Pos.setObjectName("spinBox_frameNo1Pos")
        self.label_frameNo1Pos = QtWidgets.QLabel(self.tab)
        self.label_frameNo1Pos.setGeometry(QtCore.QRect(10, 110, 91, 16))
        self.label_frameNo1Pos.setObjectName("label_frameNo1Pos")
        self.spinBox_ExposureTime1Pos = QtWidgets.QSpinBox(self.tab)
        self.spinBox_ExposureTime1Pos.setGeometry(QtCore.QRect(130, 130, 81, 22))
        self.spinBox_ExposureTime1Pos.setMaximum(999)
        self.spinBox_ExposureTime1Pos.setProperty("value", 45)
        self.spinBox_ExposureTime1Pos.setObjectName("spinBox_ExposureTime1Pos")
        self.spinBox_WaitTime1Pos = QtWidgets.QSpinBox(self.tab)
        self.spinBox_WaitTime1Pos.setGeometry(QtCore.QRect(240, 130, 81, 22))
        self.spinBox_WaitTime1Pos.setMaximum(999)
        self.spinBox_WaitTime1Pos.setProperty("value", 5)
        self.spinBox_WaitTime1Pos.setObjectName("spinBox_WaitTime1Pos")
        self.label_ExposureTime1Pos = QtWidgets.QLabel(self.tab)
        self.label_ExposureTime1Pos.setGeometry(QtCore.QRect(130, 110, 91, 16))
        self.label_ExposureTime1Pos.setObjectName("label_ExposureTime1Pos")
        self.label_WaitTime1Pos = QtWidgets.QLabel(self.tab)
        self.label_WaitTime1Pos.setGeometry(QtCore.QRect(240, 110, 91, 16))
        self.label_WaitTime1Pos.setObjectName("label_WaitTime1Pos")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.spinBox_WaitTime3Pos = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_WaitTime3Pos.setGeometry(QtCore.QRect(240, 130, 81, 22))
        self.spinBox_WaitTime3Pos.setMaximum(999)
        self.spinBox_WaitTime3Pos.setProperty("value", 5)
        self.spinBox_WaitTime3Pos.setObjectName("spinBox_WaitTime3Pos")
        self.spinBox_frameNo3Pos = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_frameNo3Pos.setGeometry(QtCore.QRect(10, 130, 81, 22))
        self.spinBox_frameNo3Pos.setMaximum(999)
        self.spinBox_frameNo3Pos.setProperty("value", 3)
        self.spinBox_frameNo3Pos.setObjectName("spinBox_frameNo3Pos")
        self.label_frameNo3Pos = QtWidgets.QLabel(self.tab_2)
        self.label_frameNo3Pos.setGeometry(QtCore.QRect(10, 110, 91, 16))
        self.label_frameNo3Pos.setObjectName("label_frameNo3Pos")
        self.pushButton_Auto3Pos = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_Auto3Pos.setGeometry(QtCore.QRect(140, 20, 171, 51))
        self.pushButton_Auto3Pos.setObjectName("pushButton_Auto3Pos")
        self.label_ExposureTime3Pos = QtWidgets.QLabel(self.tab_2)
        self.label_ExposureTime3Pos.setGeometry(QtCore.QRect(130, 110, 91, 16))
        self.label_ExposureTime3Pos.setObjectName("label_ExposureTime3Pos")
        self.label_WaitTime3Pos = QtWidgets.QLabel(self.tab_2)
        self.label_WaitTime3Pos.setGeometry(QtCore.QRect(240, 110, 91, 16))
        self.label_WaitTime3Pos.setObjectName("label_WaitTime3Pos")
        self.spinBox_ExposureTime3Pos = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_ExposureTime3Pos.setGeometry(QtCore.QRect(130, 130, 81, 22))
        self.spinBox_ExposureTime3Pos.setMaximum(999)
        self.spinBox_ExposureTime3Pos.setProperty("value", 45)
        self.spinBox_ExposureTime3Pos.setObjectName("spinBox_ExposureTime3Pos")
        self.label_3Pos = QtWidgets.QLabel(self.tab_2)
        self.label_3Pos.setGeometry(QtCore.QRect(30, 40, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3Pos.setFont(font)
        self.label_3Pos.setObjectName("label_3Pos")
        self.tabWidget.addTab(self.tab_2, "")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 430, 721, 301))
        self.tableWidget.setRowCount(9)
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(85)
        self.portNameText = QtWidgets.QLineEdit(self.centralwidget)
        self.portNameText.setEnabled(True)
        self.portNameText.setGeometry(QtCore.QRect(20, 30, 71, 20))
        self.portNameText.setReadOnly(True)
        self.portNameText.setObjectName("portNameText")
        self.baudRateText = QtWidgets.QLineEdit(self.centralwidget)
        self.baudRateText.setEnabled(True)
        self.baudRateText.setGeometry(QtCore.QRect(110, 30, 71, 20))
        self.baudRateText.setReadOnly(True)
        self.baudRateText.setObjectName("baudRateText")
        self.connectArduino = QtWidgets.QPushButton(self.centralwidget)
        self.connectArduino.setGeometry(QtCore.QRect(200, 20, 111, 31))
        self.connectArduino.setObjectName("connectArduino")
        self.disconnectArduino = QtWidgets.QPushButton(self.centralwidget)
        self.disconnectArduino.setGeometry(QtCore.QRect(320, 20, 111, 31))
        self.disconnectArduino.setObjectName("disconnectArduino")
        self.connectedBtn = QtWidgets.QRadioButton(self.centralwidget)
        self.connectedBtn.setGeometry(QtCore.QRect(440, 30, 82, 17))
        self.connectedBtn.setCheckable(False)
        self.connectedBtn.setObjectName("connectedBtn")
        self.pushButton_close = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_close.setGeometry(QtCore.QRect(800, 10, 131, 41))
        self.pushButton_close.setObjectName("pushButton_close")
        self.lineEdit_receivedSerial = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_receivedSerial.setGeometry(QtCore.QRect(530, 30, 251, 20))
        self.lineEdit_receivedSerial.setReadOnly(True)
        self.lineEdit_receivedSerial.setObjectName("lineEdit_receivedSerial")
        self.label_Port = QtWidgets.QLabel(self.centralwidget)
        self.label_Port.setGeometry(QtCore.QRect(30, 10, 71, 16))
        self.label_Port.setObjectName("label_Port")
        self.label_Baudrate = QtWidgets.QLabel(self.centralwidget)
        self.label_Baudrate.setGeometry(QtCore.QRect(120, 10, 51, 16))
        self.label_Baudrate.setObjectName("label_Baudrate")
        self.label_Baudrate_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_Baudrate_2.setGeometry(QtCore.QRect(530, 10, 121, 16))
        self.label_Baudrate_2.setObjectName("label_Baudrate_2")
        self.pushButton_saveTable = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_saveTable.setGeometry(QtCore.QRect(850, 360, 75, 23))
        self.pushButton_saveTable.setObjectName("pushButton_saveTable")
        self.pushButton_openTable = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_openTable.setGeometry(QtCore.QRect(850, 330, 75, 23))
        self.pushButton_openTable.setObjectName("pushButton_openTable")
        self.pushButton_setP1_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_setP1_1.setGeometry(QtCore.QRect(750, 460, 75, 23))
        self.pushButton_setP1_1.setObjectName("pushButton_setP1_1")
        self.pushButton_setP1_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_setP1_2.setGeometry(QtCore.QRect(750, 490, 75, 23))
        self.pushButton_setP1_2.setObjectName("pushButton_setP1_2")
        self.pushButton_setP1_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_setP1_3.setGeometry(QtCore.QRect(750, 520, 75, 23))
        self.pushButton_setP1_3.setObjectName("pushButton_setP1_3")
        self.pushButton_setP2_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_setP2_1.setGeometry(QtCore.QRect(750, 550, 75, 23))
        self.pushButton_setP2_1.setObjectName("pushButton_setP2_1")
        self.pushButton_setP2_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_setP2_2.setGeometry(QtCore.QRect(750, 580, 75, 23))
        self.pushButton_setP2_2.setObjectName("pushButton_setP2_2")
        self.pushButton_setP2_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_setP2_3.setGeometry(QtCore.QRect(750, 610, 75, 23))
        self.pushButton_setP2_3.setObjectName("pushButton_setP2_3")
        self.pushButton_setP3_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_setP3_1.setGeometry(QtCore.QRect(750, 640, 75, 23))
        self.pushButton_setP3_1.setObjectName("pushButton_setP3_1")
        self.pushButton_setP3_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_setP3_2.setGeometry(QtCore.QRect(750, 670, 75, 23))
        self.pushButton_setP3_2.setObjectName("pushButton_setP3_2")
        self.pushButton_setP3_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_setP3_3.setGeometry(QtCore.QRect(750, 700, 75, 23))
        self.pushButton_setP3_3.setObjectName("pushButton_setP3_3")
        self.label_M2_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_M2_5.setGeometry(QtCore.QRect(870, 430, 31, 16))
        self.label_M2_5.setObjectName("label_M2_5")
        self.pushButton_moveP1_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_moveP1_1.setGeometry(QtCore.QRect(850, 460, 75, 23))
        self.pushButton_moveP1_1.setObjectName("pushButton_moveP1_1")
        self.pushButton_moveP1_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_moveP1_2.setGeometry(QtCore.QRect(850, 490, 75, 23))
        self.pushButton_moveP1_2.setObjectName("pushButton_moveP1_2")
        self.pushButton_moveP1_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_moveP1_3.setGeometry(QtCore.QRect(850, 520, 75, 23))
        self.pushButton_moveP1_3.setObjectName("pushButton_moveP1_3")
        self.pushButton_moveP2_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_moveP2_1.setGeometry(QtCore.QRect(850, 550, 75, 23))
        self.pushButton_moveP2_1.setObjectName("pushButton_moveP2_1")
        self.pushButton_moveP2_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_moveP2_2.setGeometry(QtCore.QRect(850, 580, 75, 23))
        self.pushButton_moveP2_2.setObjectName("pushButton_moveP2_2")
        self.pushButton_moveP2_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_moveP2_3.setGeometry(QtCore.QRect(850, 610, 75, 23))
        self.pushButton_moveP2_3.setObjectName("pushButton_moveP2_3")
        self.pushButton_moveP3_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_moveP3_1.setGeometry(QtCore.QRect(850, 640, 75, 23))
        self.pushButton_moveP3_1.setObjectName("pushButton_moveP3_1")
        self.pushButton_moveP3_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_moveP3_2.setGeometry(QtCore.QRect(850, 670, 75, 23))
        self.pushButton_moveP3_2.setObjectName("pushButton_moveP3_2")
        self.pushButton_moveP3_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_moveP3_3.setGeometry(QtCore.QRect(850, 700, 75, 23))
        self.pushButton_moveP3_3.setObjectName("pushButton_moveP3_3")
        self.pushButton_openTableGreen660 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_openTableGreen660.setGeometry(QtCore.QRect(620, 300, 75, 23))
        self.pushButton_openTableGreen660.setObjectName("pushButton_openTableGreen660")
        self.pushButton_openTableGreen550 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_openTableGreen550.setGeometry(QtCore.QRect(620, 330, 75, 23))
        self.pushButton_openTableGreen550.setObjectName("pushButton_openTableGreen550")
        self.pushButton_openTableGreen440 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_openTableGreen440.setGeometry(QtCore.QRect(620, 360, 75, 23))
        self.pushButton_openTableGreen440.setObjectName("pushButton_openTableGreen440")
        self.pushButton_openTableGreen330 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_openTableGreen330.setGeometry(QtCore.QRect(620, 390, 75, 23))
        self.pushButton_openTableGreen330.setObjectName("pushButton_openTableGreen330")
        self.label_M2_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_M2_6.setGeometry(QtCore.QRect(750, 430, 91, 20))
        self.label_M2_6.setObjectName("label_M2_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(569, 290, 131, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(709, 290, 121, 131))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_openTableBlue660 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_openTableBlue660.setGeometry(QtCore.QRect(40, 10, 75, 23))
        self.pushButton_openTableBlue660.setObjectName("pushButton_openTableBlue660")
        self.pushButton_openTableBlue550 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_openTableBlue550.setGeometry(QtCore.QRect(40, 40, 75, 23))
        self.pushButton_openTableBlue550.setObjectName("pushButton_openTableBlue550")
        self.pushButton_openTableBlue440 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_openTableBlue440.setGeometry(QtCore.QRect(40, 70, 75, 23))
        self.pushButton_openTableBlue440.setObjectName("pushButton_openTableBlue440")
        self.pushButton_openTableBlue330 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_openTableBlue330.setGeometry(QtCore.QRect(40, 100, 75, 23))
        self.pushButton_openTableBlue330.setObjectName("pushButton_openTableBlue330")
        self.groupBox_2.raise_()
        self.sliderM1_phase.raise_()
        self.sliderM1_x.raise_()
        self.sliderM1_y.raise_()
        self.spinBox_M1_phase.raise_()
        self.spinBox_M1_x.raise_()
        self.spinBox_M1_y.raise_()
        self.spinBox_M1_1.raise_()
        self.spinBox_M1_2.raise_()
        self.spinBox_M1_3.raise_()
        self.spinBox_M1_4.raise_()
        self.label_M1_1.raise_()
        self.label_M1_2.raise_()
        self.label_M1_3.raise_()
        self.label_M1_4.raise_()
        self.label_M1_phase.raise_()
        self.label_M1_x.raise_()
        self.label_M1_y.raise_()
        self.spinBox_M2_1.raise_()
        self.label_M2_x.raise_()
        self.sliderM2_x.raise_()
        self.spinBox_M2_4.raise_()
        self.label_M2_phase.raise_()
        self.label_M2_2.raise_()
        self.sliderM2_phase.raise_()
        self.spinBox_M2_3.raise_()
        self.spinBox_M2_y.raise_()
        self.spinBox_M2_x.raise_()
        self.label_M2_1.raise_()
        self.label_M2_y.raise_()
        self.spinBox_M2_phase.raise_()
        self.spinBox_M2_2.raise_()
        self.label_M2_3.raise_()
        self.label_M2_4.raise_()
        self.sliderM2_y.raise_()
        self.groupBox.raise_()
        self.tableWidget.raise_()
        self.portNameText.raise_()
        self.baudRateText.raise_()
        self.connectArduino.raise_()
        self.disconnectArduino.raise_()
        self.connectedBtn.raise_()
        self.pushButton_close.raise_()
        self.lineEdit_receivedSerial.raise_()
        self.label_Port.raise_()
        self.label_Baudrate.raise_()
        self.label_Baudrate_2.raise_()
        self.pushButton_saveTable.raise_()
        self.pushButton_openTable.raise_()
        self.pushButton_setP1_1.raise_()
        self.pushButton_setP1_2.raise_()
        self.pushButton_setP1_3.raise_()
        self.pushButton_setP2_1.raise_()
        self.pushButton_setP2_2.raise_()
        self.pushButton_setP2_3.raise_()
        self.pushButton_setP3_1.raise_()
        self.pushButton_setP3_2.raise_()
        self.pushButton_setP3_3.raise_()
        self.label_M2_5.raise_()
        self.pushButton_moveP1_1.raise_()
        self.pushButton_moveP1_2.raise_()
        self.pushButton_moveP1_3.raise_()
        self.pushButton_moveP2_1.raise_()
        self.pushButton_moveP2_2.raise_()
        self.pushButton_moveP2_3.raise_()
        self.pushButton_moveP3_1.raise_()
        self.pushButton_moveP3_2.raise_()
        self.pushButton_moveP3_3.raise_()
        self.pushButton_openTableGreen660.raise_()
        self.pushButton_openTableGreen550.raise_()
        self.pushButton_openTableGreen440.raise_()
        self.pushButton_openTableGreen330.raise_()
        self.label_M2_6.raise_()
        self.groupBox_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 947, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.spinBox_M1_phase.valueChanged['int'].connect(self.sliderM1_phase.setValue)
        self.spinBox_M1_x.valueChanged['int'].connect(self.sliderM1_x.setValue)
        self.spinBox_M1_y.valueChanged['int'].connect(self.sliderM1_y.setValue)
        self.sliderM1_x.valueChanged['int'].connect(self.spinBox_M1_x.setValue)
        self.sliderM1_phase.valueChanged['int'].connect(self.spinBox_M1_phase.setValue)
        self.sliderM1_y.valueChanged['int'].connect(self.spinBox_M1_y.setValue)
        self.sliderM2_phase.valueChanged['int'].connect(self.spinBox_M2_phase.setValue)
        self.sliderM2_x.valueChanged['int'].connect(self.spinBox_M2_x.setValue)
        self.sliderM2_y.valueChanged['int'].connect(self.spinBox_M2_y.setValue)
        self.spinBox_M2_phase.valueChanged['int'].connect(self.sliderM2_phase.setValue)
        self.spinBox_M2_x.valueChanged['int'].connect(self.sliderM2_x.setValue)
        self.spinBox_M2_y.valueChanged['int'].connect(self.sliderM2_y.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_M1_1.setText(_translate("MainWindow", "M1 - 1"))
        self.label_M1_2.setText(_translate("MainWindow", "M1 - 2"))
        self.label_M1_3.setText(_translate("MainWindow", "M1 - 3"))
        self.label_M1_4.setText(_translate("MainWindow", "M1 - 4"))
        self.label_M1_phase.setText(_translate("MainWindow", "M1 - phase"))
        self.label_M1_x.setText(_translate("MainWindow", "M1 - x"))
        self.label_M1_y.setText(_translate("MainWindow", "M1 - y"))
        self.label_M2_x.setText(_translate("MainWindow", "M2 - x"))
        self.label_M2_phase.setText(_translate("MainWindow", "M2 - phase"))
        self.label_M2_2.setText(_translate("MainWindow", "M2 - 2"))
        self.label_M2_1.setText(_translate("MainWindow", "M2 - 1"))
        self.label_M2_y.setText(_translate("MainWindow", "M2 - y"))
        self.label_M2_3.setText(_translate("MainWindow", "M2 - 3"))
        self.label_M2_4.setText(_translate("MainWindow", "M2 - 4"))
        self.groupBox.setTitle(_translate("MainWindow", "Automated capture"))
        self.checkBox_pos1.setText(_translate("MainWindow", "Position 1"))
        self.checkBox_pos2.setText(_translate("MainWindow", "Position 2"))
        self.checkBox_pos3.setText(_translate("MainWindow", "Position 3"))
        self.pushButton_Auto1Pos.setText(_translate("MainWindow", "Start automated run"))
        self.label_frameNo1Pos.setText(_translate("MainWindow", "Number of frames"))
        self.label_ExposureTime1Pos.setText(_translate("MainWindow", "Exposure time (ms)"))
        self.label_WaitTime1Pos.setText(_translate("MainWindow", "Wait time (ms)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Single Position automated"))
        self.label_frameNo3Pos.setText(_translate("MainWindow", "Number of frames"))
        self.pushButton_Auto3Pos.setText(_translate("MainWindow", "Start automated run"))
        self.label_ExposureTime3Pos.setText(_translate("MainWindow", "Exposure time (ms)"))
        self.label_WaitTime3Pos.setText(_translate("MainWindow", "Wait time (ms)"))
        self.label_3Pos.setText(_translate("MainWindow", "All 3 positions"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "3 Positions automated"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "P1-1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "P1-2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "P1-3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "P2-1"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "P2-2"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "P2-3"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "P3-1"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "P3-2"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "P3-3"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "M1-1"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "M1-2"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "M1-3"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "M1-4"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "M2-1"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "M2_1"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "M2-3"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "M2-4"))
        self.connectArduino.setText(_translate("MainWindow", "Connect to Arduino"))
        self.disconnectArduino.setText(_translate("MainWindow", "Disconnect Arduino"))
        self.connectedBtn.setText(_translate("MainWindow", "connected"))
        self.pushButton_close.setText(_translate("MainWindow", "Close"))
        self.label_Port.setText(_translate("MainWindow", "Arduino Port"))
        self.label_Baudrate.setText(_translate("MainWindow", "Baudrate"))
        self.label_Baudrate_2.setText(_translate("MainWindow", "Received Serial string"))
        self.pushButton_saveTable.setText(_translate("MainWindow", "Save Table"))
        self.pushButton_openTable.setText(_translate("MainWindow", "Open Table"))
        self.pushButton_setP1_1.setText(_translate("MainWindow", "Set P1-1"))
        self.pushButton_setP1_2.setText(_translate("MainWindow", "Set P1-2"))
        self.pushButton_setP1_3.setText(_translate("MainWindow", "Set P1-3"))
        self.pushButton_setP2_1.setText(_translate("MainWindow", "Set P2-1"))
        self.pushButton_setP2_2.setText(_translate("MainWindow", "Set P2-2"))
        self.pushButton_setP2_3.setText(_translate("MainWindow", "Set P2-3"))
        self.pushButton_setP3_1.setText(_translate("MainWindow", "Set P3-1"))
        self.pushButton_setP3_2.setText(_translate("MainWindow", "Set P3-2"))
        self.pushButton_setP3_3.setText(_translate("MainWindow", "Set P3-3"))
        self.label_M2_5.setText(_translate("MainWindow", "Move"))
        self.pushButton_moveP1_1.setText(_translate("MainWindow", "Move P1-1"))
        self.pushButton_moveP1_2.setText(_translate("MainWindow", "Move P1-2"))
        self.pushButton_moveP1_3.setText(_translate("MainWindow", "Move P1-3"))
        self.pushButton_moveP2_1.setText(_translate("MainWindow", "Move P2-1"))
        self.pushButton_moveP2_2.setText(_translate("MainWindow", "Move P2-2"))
        self.pushButton_moveP2_3.setText(_translate("MainWindow", "Move P2-3"))
        self.pushButton_moveP3_1.setText(_translate("MainWindow", "Move P3-1"))
        self.pushButton_moveP3_2.setText(_translate("MainWindow", "Move P3-2"))
        self.pushButton_moveP3_3.setText(_translate("MainWindow", "Move P3-3"))
        self.pushButton_openTableGreen660.setText(_translate("MainWindow", "Open 660"))
        self.pushButton_openTableGreen550.setText(_translate("MainWindow", "Open 550"))
        self.pushButton_openTableGreen440.setText(_translate("MainWindow", "Open 440"))
        self.pushButton_openTableGreen330.setText(_translate("MainWindow", "Open 330"))
        self.label_M2_6.setText(_translate("MainWindow", "Set to current Pos"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Green"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Blue"))
        self.pushButton_openTableBlue660.setText(_translate("MainWindow", "Open 660"))
        self.pushButton_openTableBlue550.setText(_translate("MainWindow", "Open 550"))
        self.pushButton_openTableBlue440.setText(_translate("MainWindow", "Open 440"))
        self.pushButton_openTableBlue330.setText(_translate("MainWindow", "Open 330"))

